version: "3"

services:
  web:
    build: ./app
    read_only: false
    command: poetry run python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=django_app
      - POSTGRES_PASSWORD=91371104
      - POSTGRES_DB=django_app_dev
    ports:
      - "54322:5432"


volumes:
  postgres_data: